services:
  db:
    image: postgres:18

    container_name: vivvo_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vivvo_dev

    ports:
      - "5432:5432"
